# Generated by Django 4.1.3 on 2022-11-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'get_latest_by': ['date_joined'], 'ordering': ['date_joined'], 'verbose_name': 'user', 'verbose_name_plural': "user's"},
        ),
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='user_picture/%Y/%m/%d'),
        ),
    ]
